---
title: "Untitled"
author: "Dennis"
date: "7/29/2020"
output: html_document
---

# potential fig.5: histogram

fig. a)

Beta = c(0,0.1,0.3) given cM = 0.1, alpha =0.1, cT = 0.9 constant 

beta  cT    M            R
0.0 0.9 0.1764824 0.8235176
0.1 0.9 0.7216596 0.2783404
0.2 0.9 0.7216326 0.2783674
0.3 0.9 1.0000000 0.0000000

```{r}
# cM = 0.2 
pacman::p_load(dplyr)

M <- c(0.1764824,0.7216596,0.7216326,1.0000000)

R <- c(0.8235176,0.2783404,0.2783674,0.0000000)
  
df_beta1 <- data.frame(M,R)
bt1df <- stack(df_beta1) # stack the data
bt1df$beta <- c(0,0.1,0.2,0.3,0,0.1,0.2,0.3)
bt1df
```

fig. b)

Beta = c(0,0.1,0.3) given cM = 0.3, alpha =0.1, cT = 0.9 constant 

beta  cT    M            R
0.0 0.9 0.008507255 0.9914927
0.1 0.9 0.362779590 0.6372204
0.2 0.9 0.362665887 0.6373341
0.3 0.9 0.000000000 1.0000000

```{r}
# cM = 0.5 

M <- c(0.008507255,0.362779590,0.362665887,0.000000000)

R <- c(0.9914927,0.6372204,0.6373341,1.0000000)
  
df_beta2 <- data.frame(M,R)
bt2df <- stack(df_beta2) # stack the data
bt2df$beta <- c(0,0.1,0.2,0.3,0,0.1,0.2,0.3)
bt2df
```

```{r}
library(gridExtra)
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
```


```{r}
# ggplot 
pacman::p_load(ggplot2,gridExtra,reshape2,envalysis)
theme_set(theme_publish())  
a <- ggplot(bt1df,aes(x=beta,y=values,fill = ind)) + geom_col(position = "dodge",colour= "black") + ylim(c(0,1)) + labs(y="Fraction of partially migratory population") + scale_x_continuous(expression(paste("Transmission",~(beta))),labels=as.character(bt1df$beta),breaks=bt1df$beta) + scale_fill_manual(name="Groups",breaks=c("M","R"),labels=c("Migrant","Resident"),values= c("#f7fcb9","#31a354"))+ggtitle(expression(paste((a)~~~c[M]==0.1)))+theme(legend.position = "none")

b<- ggplot(bt2df,aes(x=beta,y=values,fill = ind)) + geom_col(position = "dodge",colour= "black") + ylim(c(0,1)) + scale_x_continuous(expression(paste("Transmission",~(beta))),labels=as.character(bt2df$beta),breaks=bt2df$beta) + scale_fill_manual(name="Groups",breaks=c("M","R"),labels=c("Migrant","Resident"),values= c("#f7fcb9","#31a354"))+ggtitle(expression(paste((b)~~~c[M]==0.3))) + theme(axis.title.y = element_blank())
legend <- get_legend(b)

b <- b + theme(legend.position = "none")
```

```{r,width = 10, height = 4}
grid.arrange(a,b,legend, ncol=2, nrow = 2,layout_matrix = rbind(c(1,2), c(3,3)), widths = c(2.7, 2.7), heights = c(0.4, 0.02))
g <- arrangeGrob(a,b,legend, ncol=2, nrow = 2,layout_matrix = rbind(c(1,2), c(3,3)), widths = c(2.7, 2.7), heights = c(0.4, 0.02))
ggsave("fig5.png",g, width = 10, height = 4)
```
