---
title: "fig3"
author: "Dennis"
date: "7/1/2020"
output: html_document
---

# potential fig.3: histogram

cT = c(0.2,0.5,0.8) given cM = 0.2 constant 

cM   cT   M            R
0.2  0.9  0.394576707  0.6054233
0.2  0.8  0.471076535  0.5289235
0.2  0.7  0.473673742  0.5263263
0.2  0.6  0.464105142  0.5358949
0.2  0.5  0.447957223  0.5520428
0.2  0.4  0.405096390  0.5949036
0.2  0.3  0.294346795  0.7056532
0.2  0.2  0.112225253  0.8877747
0.2  0.1  0.069886546  0.9301135
0.2  0.0  0.070527588  0.9294724

```{r}
# data wranggling
pacman::p_load(dplyr)

M <- c(0.069886546, 0.447957223, 0.394576707)

R <- c(0.9301135, 0.5520428, 0.6054233)
  
df <- data.frame(M,R)
sdf <- stack(df) # stack the data
sdf$cT <- c(0.1,0.5,0.9,0.1,0.5,0.9)
sdf
```

```{r}
# ggplot 
pacman::p_load(ggplot2,gridExtra,reshape2,envalysis)
theme_set(theme_publish()) 
fig3 <- ggplot(sdf,aes(x=cT,y=values,fill = ind)) + geom_col(position = "dodge",colour= "black") + ylim(c(0,1)) + labs(y="Fraction of partially migratory population",x="cT variation") + scale_x_continuous(expression(paste("Fecundity cost of tolerance",~(c[T]))),labels=as.character(sdf$cT),breaks=sdf$cT) + scale_fill_manual(name="Groups",breaks=c("M","R"),labels=c("Migrant","Resident"),values= c("#f7fcb9","#31a354"))
fig3
ggsave("fig3.png",width = 8, height = 5)
```